---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uibranding
  labels:
    app: uibranding
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uibranding
  template:
    metadata:
      labels:
        app: uibranding
        service: uibranding
        version: uibranding
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
       -  name : zero-uibranding
          image: ghcr.io/manu-mishra/zero-uibranding:0.0.2741930350
          imagePullPolicy: Always
          ports:
           -  containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "124Mi"
              cpu: "10m"
      imagePullSecrets:
       -  name: private-repo-secret
      serviceAccountName: uibranding
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uibranding
---
apiVersion: v1
kind: Service
metadata:
  name: uibranding
  labels:
    app: uibranding
    service: uibranding
spec:
  ports:
    - name: http-uibranding
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: uibranding