apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: zero-proxy-appsetting
  behavior: replace
  files:
    - appsettings.json
patchesStrategicMerge:
- patch_container_image.yaml
